{
 "title": "Bililive Dashboards",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "bgo_live_status" } },
   { "name": "anchor", "query": { "query": "bgo_live_status" } }
  ]
 },
 "panels": [
  {
   "title": "Live Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bgo_live_status{instance=~\"$instance\", live_host_name=~\"$anchor\"}",
     "legendFormat": "{{live_host_name}}"
    }
   ]
  },
  {
   "title": "Length of live stream in the past 30 days",
   "type": "stat",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(live_host_name)(increase(bgo_live_duration_seconds{instance=~\"$instance\", live_host_name=~\"$anchor\"}[30d]))",
     "legendFormat": "{{live_host_name}}"
    }
   ]
  },
  {
   "title": "Output File Size",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bgo_recorder_total_bytes{instance=~\"$instance\", live_host_name=~\"$anchor\"}",
     "legendFormat": "{{live_host_name}}"
    }
   ]
  },
  {
   "title": "Live Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(bgo_recorder_total_bytes{instance=~\"$instance\", live_host_name=~\"$anchor\"}[$__interval])",
     "legendFormat": "{{live_host_name}}"
    }
   ]
  }
 ]
}